language: go
go:
- 1.3.1
- tip
env:
- PATH=$HOME/gopath/bin:$PATH
script:
- git config --global url.git@github.com:.insteadof https://github.com/
- make build
- make test
notifications:
  email: false
  slack:
    secure: AllObcfdayYCKOfiyGGn3F3otlv48XY8YHyWM1h6tMidC4kTCTNC+C0AMLdzETELPlCCQsKgwCujNWite3ohQdHw62fHLnBsZ05ttmjHnhrYha/kKK2fyKnBiXN5QWYScwgsiGU6JWPJXxGjZ3zS4tfVR9zNPqnkRMfppPArnsY=
